name: Feature Request
description: Suggest an idea for this project
title: '[Feature Request]: '
labels:
  - enhancement
  - needs triage
body:
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of the problem or missing capability
    validations:
      required: true
